services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: reminder-app
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - reminder

  nginx:
    image: nginx:alpine
    container_name: reminder-nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - reminder

  db:
    image: mysql:8.0
    container_name: p-db
    environment:
      MYSQL_DATABASE: reminder
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: reminder
      MYSQL_PASSWORD: reminder
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - reminder

networks:
  reminder:

volumes:
  dbdata:
